version: '3'
services:
  web:
    container_name: webdocker-user16
    image: igossoudarev/webdocker111124:linux
  sidecar:
    container_name: sidecar-user16
    image: nginx
    ports:
      - 16443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/ssl/server.crt
      - ./server.key:/etc/ssl/server.key
